baseURL = "http://intranet.aiotools.ovh"
paginate = 50
languageCode = "fr-fr"
theme = "dream"
title = "AIO"



[[menu.main]]
name = "Sécurité & Conditions sanitaires"
url = "/conditions-sanitaires/"
weight = 1
identifier = "securite-conditions-sanitaires"

[[menu.main]]
name = "5S sanitaires"
url = "/conditions-sanitaires/5s-sanitaires/"
weight = 1
identifier = "5S-sanitaires"
parent = "securite-conditions-sanitaires"

[[menu.main]]
name = "Plan suspicion COVID-19"
url = "/conditions-sanitaires/covid-19/"
weight = 2
identifier = "covid-19"
parent = "securite-conditions-sanitaires"



[[menu.main]]
name = "CSE"
url = "/cse/"
weight = 6
identifier = "cse"



[[menu.main]]
name = "Rester à flot"
url = "/rester-a-flot/"
weight = 5
identifier = "rester-flot"




[[menu.main]]
name = "Soutenir l'activité"
url = "/soutenir-l-activite/"
weight = 2
identifier = "soutenir-activite"

[[menu.main]]
name = "Livrer les clients"
url = "/soutenir-l-activite/livrer-les-clients/"
weight = 1
identifier = "livrer-les-clients"
parent = "soutenir-activite"

[[menu.main]]
name = "Obtenir des commandes"
url = "/soutenir-l-activite/obtenir-des-commandes/"
weight = 2
identifier = "obtenir-des-commandes"
parent = "soutenir-activite"

[[menu.main]]
name = "Améliorer nos produits"
url = "/soutenir-l-activite/ameliorer-nos-produits/"
weight = 3
identifier = "ameliorer-nos-produits"
parent = "soutenir-activite"



[[menu.main]]
name = "Vivre ensemble"
url = "/vivre-ensemble/"
weight = 4
identifier = "vivre-ensemble"

[[menu.main]]
name = "Apprendre à créer le lien avec le digital"
url = "/vivre-ensemble/apprendre-a-creer-le-lien-avec-le-digital/"
weight = 1
identifier = "apprendre-a-creer-le-lien-avec-le-digital"
parent = "vivre-ensemble"

[[menu.main]]
name = "Fêter nos succès"
url = "/vivre-ensemble/feter-nos-succes/"
weight = 2
identifier = "feter-nos-succes"
parent = "vivre-ensemble"



[[menu.main]]
name = "Développement de nouveaux produits"
pre = "<i class='fa fa-heart'></i>"
url = "/developpement-de-nouveaux-produits/"
weight = 3
identifier = "developpement-de-nouveaux-produits"

[[menu.main]]
name = "Des produits pour lutter contre le COVID"
url = "/developpement-de-nouveaux-produits/lutte-contre-covid/"
weight = 1
identifier = "lutte-contre-covid"
parent = "developpement-de-nouveaux-produits"

[[menu.main]]
name = "Améliorer la formation et le développement du KKR"
url = "/developpement-de-nouveaux-produits/ameliorer-la-formation-et-le-developpement-du-KKR/"
weight = 2
identifier = "ameliorer-la-formation-et-le-developpement-du-KKR"
parent = "developpement-de-nouveaux-produits"

[[menu.main]]
name = "Produire en France et EU"
url = "/developpement-de-nouveaux-produits/produire-en-france-eu/"
weight = 3
identifier = "produire-en-france-eu"
parent = "developpement-de-nouveaux-produits"

[[menu.main]]
name = "Comprendre le geste"
url = "/developpement-de-nouveaux-produits/comprendre-le-geste/"
weight = 4
identifier = "comprendre-le-geste"
parent = "developpement-de-nouveaux-produits"




[params]
author = "AIO intern"
avatar = "/AIO-logo.png"
backgroundImage = "/background.jpg"
dark404Button = true
darkLinkColor = "darkseagreen"
darkNav = false
email = "florian.boudinet@aio.eu"
linkColor = "mediumaquamarine"
motto = "AIO"
siteStartYear = 2020
custom_css = ["/css/aio.css"]
